import type { WeeklyAssessment } from "@/lib/insights/weekly";
import { BEHAVIORS_BY_ID } from "@/lib/journal/behaviors";
import { cn } from "@/lib/utils";

type Props = {
  assessment: WeeklyAssessment;
  period: string;
  label: string;
};

export function AssessmentReport({ assessment, label }: Props) {
  const range = formatRange(assessment.weekStart, assessment.weekEnd);

  return (
    <div className="space-y-6 print:space-y-5">
      {/* ── Hero (visible only in print — screen shows it in AssessmentClient header) ── */}
      <header className="hidden print:block border-b border-border pb-4">
        <p className="text-xs uppercase tracking-[0.25em] text-fg-muted">Woop · Performance Assessment</p>
        <h1 className="font-stat text-4xl mt-1">{label}</h1>
        <p className="text-sm text-fg-muted mt-1">{range} · {assessment.daysLogged}/7 days logged</p>
      </header>

      {/* Days logged (screen only) */}
      <p className="text-sm text-fg-muted print:hidden">
        {range} · <span className="text-fg">{assessment.daysLogged}</span>/7 days logged
      </p>

      {/* ── 3-column stats ── */}
      <div className="grid grid-cols-3 gap-4 rounded-2xl border border-border bg-surface p-5">
        <Stat label="Recovery" value={assessment.recoveryAvg} unit="%" delta={assessment.recoveryDelta} color="text-recovery-high" />
        <Stat label="Sleep" value={assessment.sleepAvg} unit="%" delta={assessment.sleepDelta} color="text-sleep" />
        <Stat label="Strain" value={assessment.strainAvg} unit="" delta={assessment.strainDelta} color="text-strain" />
      </div>

      {/* ── Highlights ── */}
      <section className="rounded-2xl border border-border bg-surface p-5 space-y-2">
        <h2 className="text-xs uppercase tracking-widest text-fg-muted">Highlights</h2>
        <ul className="space-y-2">
          {assessment.highlights.map((h, i) => (
            <li key={i} className="flex gap-2 text-sm">
              <span className="text-fg-dim mt-0.5">—</span>
              <span>{h}</span>
            </li>
          ))}
        </ul>
      </section>

      {/* ── Behavior influences ── */}
      {(assessment.topBehavior || assessment.worstBehavior) && (
        <section className="rounded-2xl border border-border bg-surface p-5 space-y-3">
          <h2 className="text-xs uppercase tracking-widest text-fg-muted">Behavior influences</h2>
          <div className="grid grid-cols-2 gap-4">
            {assessment.topBehavior && (
              <BehaviorCallout
                label="Most positive"
                row={assessment.topBehavior}
                positive
              />
            )}
            {assessment.worstBehavior && (
              <BehaviorCallout
                label="Most negative"
                row={assessment.worstBehavior}
                positive={false}
              />
            )}
          </div>
        </section>
      )}

      {/* ── Footer (print only) ── */}
      <footer className="hidden print:block border-t border-border pt-4 text-[10px] text-fg-dim">
        Generated by Woop · {new Date().toLocaleDateString(undefined, {
          weekday: "long", year: "numeric", month: "long", day: "numeric",
        })}
      </footer>
    </div>
  );
}

function Stat({
  label, value, unit, delta, color,
}: {
  label: string;
  value: number | null;
  unit: string;
  delta: number | null;
  color: string;
}) {
  return (
    <div>
      <div className="text-[11px] uppercase tracking-widest text-fg-muted">{label}</div>
      <div className={cn("font-stat text-3xl mt-1", color)}>
        {value !== null ? `${value}${unit}` : "—"}
      </div>
      {delta !== null && (
        <div className={cn(
          "text-[11px] uppercase tracking-widest mt-1",
          delta > 0 ? "text-recovery-high" : delta < 0 ? "text-recovery-low" : "text-fg-dim",
        )}>
          {delta > 0 ? "+" : ""}{delta}{unit} vs prev week
        </div>
      )}
    </div>
  );
}

function BehaviorCallout({
  label, row, positive,
}: {
  label: string;
  row: NonNullable<WeeklyAssessment["topBehavior"]>;
  positive: boolean;
}) {
  const meta = BEHAVIORS_BY_ID[row.behaviorId];
  return (
    <div className="rounded-xl border border-border bg-surface-2 p-3 space-y-1">
      <div className="text-[11px] uppercase tracking-widest text-fg-muted">{label}</div>
      <div className="flex items-center gap-2">
        <span className="text-xl leading-none">{meta?.emoji ?? "•"}</span>
        <span className="text-sm font-medium">{meta?.label ?? row.behaviorId}</span>
      </div>
      <div className={cn("text-xs", positive ? "text-recovery-high" : "text-recovery-low")}>
        {row.delta > 0 ? "+" : ""}{row.delta.toFixed(1)}% recovery next morning
      </div>
    </div>
  );
}

function formatRange(start: string, end: string): string {
  const s = new Date(`${start}T00:00:00`);
  const e = new Date(`${end}T00:00:00`);
  const fmt = (d: Date) => d.toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" });
  return `${fmt(s)} – ${fmt(e)}`;
}
